FROM vfarcic/jenkins

COPY var/jenkins_home/jenkins.plugins.slack.SlackNotifier.xml /usr/share/jenkins/ref/jenkins.plugins.slack.SlackNotifier.xml
COPY var/jenkins_home/jobs/devops22-infra/config.xml /usr/share/jenkins/ref/jobs/devops22-infra/config.xml
