version: '3.1'

services:

  main:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://${JENKINS_IP}/jenkins -labels 'prod' -executors 4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    secrets:
      - jenkins-user
      - source: jenkins-pass
        mode: 0400
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

