version: '3.1'

services:

  main:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://${JENKINS_IP}/jenkins -labels 'docker' -executors 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      mode: global

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

