version: '3'

services:

  main:
    image: jenkinsci/jenkins:${TAG:-2.32.3-alpine}
    ports:
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
    volumes:
      - main:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080

volumes:
  main:
    driver: rexray

networks:
  proxy:
    external: true
