version: "3.1"

services:

  jenkins-master:
    image: vfarcic/jenkins:${TAG:-latest}
    ports:
      - 50000:50000
    volumes:
      - jm:/var/jenkins_home
      - jmshare:/usr/share/jenkins/ref
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1000M
    secrets:
      - jenkins-user
      - jenkins-pass

networks:
  proxy:
    external: true

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jm:
    driver: cloudstor:aws
    driver_opts:
      size: "25"
    external: false
  jmshare:
    driver: cloudstor:aws
    driver_opts:
      size: "10"
    external: false