version: "3.1"

services:

  master:
    image: vfarcic/jenkins:${TAG:-latest}
    ports:
      - 50000:50000
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
      - default
    volumes:
      - jm:/var/jenkins_home
      - jmshare:/usr/share/jenkins/ref
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1000M
    secrets:
      - jenkins-user
      - jenkins-pass

  agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://master:8080/jenkins ${AGENT_LABELS} -executors 3
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
      - cluster-info.properties
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1000M


networks:
  proxy:
    external: true
  default:
    external: false

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
  cluster-info.properties:
    external: true

volumes:
  jm:
    driver: cloudstor:aws
    external: false
  jmshare:
    driver: cloudstor:aws
    external: false