version: "3.1"

services:

  jenkins-master:
    image: ${HUB_USER:-vfarcic}/jenkins:${TAG:-latest}
    ports:
      - 50000:50000
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
    volumes:
      - jm:/var/jenkins_home
      - jmshare:/usr/share/jenkins/ref
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1000M
    secrets:
      - jenkins-user
      - jenkins-pass

  jenkins-agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins-master:8080/jenkins -labels "prod" -executors 2
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1000M

networks:
  proxy:
    external: true

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jm:
    driver: cloudstor:aws
    driver_opts:
      size: "25"
    external: false
  jmshare:
    driver: cloudstor:aws
    driver_opts:
      size: "10"
    external: false